const tintColorLight = '#2f95dc';
const tintColorDark = '#fff';

export default {
  light: {
    text: '#000',
    background: '#fff',
    tint: tintColorLight,
    tabIconDefault: '#ccc',
    tabIconSelected: tintColorLight,
    primaryButton: '#333',
    secondaryButton: '#555',
    tertiaryButton: '#777',
    buttonText: '#fff',
    textInputBorder: '#ccc',
    textInputBackground: '#f9f9f9',
    textInputPlaceholder: 'rgba(0, 0, 0, 0.5)',
    title: '#000',
    legend: '#666',
    fieldLabel: '#333',
    hyperlink: '#007AFF',
    footerBackground: '#f0f0f0',
    separator: '#eee',
    buttonOutline: '#ccc',
    iconColor: '#333',
  },
  dark: {
    text: '#fff',
    background: '#191919',
    tint: tintColorDark,
    tabIconDefault: '#ccc',
    tabIconSelected: tintColorDark,
    primaryButton: '#444',
    secondaryButton: '#666',
    tertiaryButton: '#888',
    buttonText: '#fff',
    textInputBorder: '#555',
    textInputBackground: '#1a1a1a',
    textInputPlaceholder: 'rgba(255, 255, 255, 0.6)',
    title: '#fff',
    legend: '#aaa',
    fieldLabel: '#ccc',
    hyperlink: '#4a90e2',
    footerBackground: '#1a1a1a',
    separator: 'rgba(255,255,255,0.1)',
    buttonOutline: '#555',
    iconColor: '#444',
  },
};
